### ISSUE TITLE
adonis-version in package-json

### ISSUE THREAD

**Issue by Maxximus007** [iamraphson/adonisjs-hackathon-starter#4]
Hi,

Perhaps you can change the adonis-version in package.json to 4.1 as well. This ensures that updates of dependencies will be in line.

In the readme it might be wise to change all 4.0 references to 4.1

Furthermore, on a fresh install `adonis migration:run` gives errors with knex, did not yet found out why.

**Comment by Maxximus007** [comment]
Hi, in migrations you are using
`this.createTableIfNotExists('users', table => {`

This has been changed to:
`this.createIfNotExists('users', (table) => {`

**Comment by iamraphson** [comment]
@Maxximus007 Thanks. I have fixed all the issue here.

`adonis migration:run` is flagging an error or warning @Maxximus007. 

If it is warning check https://github.com/adonisjs/adonis-lucid/issues/304 

According to https://github.com/tgriesser/knex/issues/2489 , it's been fixed in 0.14.4 which the project is using but the warning is still there.

**Comment by iamraphson** [comment]
@Maxximus007 the error is normal..
